-- Disable Row Level Security (RLS) for all tables
-- This allows direct access via API without RLS policies

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE worker_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE reputation_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_subscriptions DISABLE ROW LEVEL SECURITY;
